/* Who can turn up in the bottom-right corner of home.

   One is drawn at random on every visit, weighted: Mr. Saturn and the
   party often, the townspeople and the enemies now and then, a few rare
   ones hardly ever. Each is a strip of eight frames, all one size — back,
   right, front, left, two of each — cut from the EarthBound sheets on The
   Spriters Resource into images/eb/cast/; the enemies that never walk in
   the game repeat their one or two frames, and every frame keeps a clear
   pixel either side so the next one along can never bleed in. w and h are
   a frame's size in the sprite's own pixels, w 18 unless given, and a
   strip lives at images/eb/cast/<id>.png unless src says otherwise. What
   everyone says is in cast-lines.json, fetched only when it is wanted. */
export const CAST = [
  { id: 'saturn', name: 'Mr. Saturn', src: 'images/eb/saturn.png', h: 22, weight: 4, font: 'saturn' },
  /* the party */
  { id: 'ness', name: 'Ness', h: 24, weight: 2 },
  { id: 'paula', name: 'Paula', h: 24, weight: 2 },
  { id: 'jeff', name: 'Jeff', h: 24, weight: 2 },
  { id: 'poo', name: 'Poo', h: 24, weight: 2 },
  /* people with names */
  { id: 'captain-strong', name: 'Captain Strong', h: 24 },
  { id: 'pokey', name: 'Pokey', h: 24, weight: 0.5 },
  { id: 'king', name: 'King', w: 26, h: 20 },
  { id: 'bubble-monkey', name: 'Bubble Monkey', h: 23 },
  { id: 'tony', name: 'Tony', h: 24 },
  { id: 'picky', name: 'Picky', h: 22 },
  { id: 'brick-road', name: 'Brick Road', h: 24 },
  { id: 'tenda', name: 'Tenda', h: 17 },
  { id: 'everdred', name: 'Everdred', h: 24, weight: 0.5 },
  { id: 'the-star-master', name: 'The Star Master', h: 24, weight: 0.25 },
  { id: 'hint-man', name: 'Hint Man', h: 24 },
  { id: 'nesss-mom', name: "Ness's Mom", h: 24 },
  { id: 'tracy', name: 'Tracy', h: 24 },
  { id: 'arms-dealer', name: 'Arms Dealer', h: 24 },
  { id: 'escargo-express-delivery-man', name: 'Escargo Express Delivery Man', h: 24 },
  { id: 'slot-machine-brother', name: 'Slot Machine Brother', h: 24 },
  { id: 'gonzales', name: 'Gonzales', h: 24 },
  { id: 'aloysius-minch', name: 'Aloysius Minch', h: 24 },
  { id: 'lardna-minch', name: 'Lardna Minch', h: 24 },
  { id: 'frank-fly', name: 'Frank Fly', h: 24 },
  { id: 'mr-carpainter', name: 'Mr. Carpainter', h: 24 },
  { id: 'dr-andonuts', name: 'Dr. Andonuts', h: 23, weight: 0.5 },
  { id: 'runaway-five', name: 'Runaway Five', h: 23, weight: 0.25 },
  { id: 'runaway-five-2', name: 'Runaway Five', h: 24, weight: 0.25 },
  { id: 'runaway-five-3', name: 'Runaway Five', h: 23, weight: 0.25 },
  { id: 'runaway-five-4', name: 'Runaway Five', h: 23, weight: 0.25 },
  /* enemies */
  { id: 'runaway-dog', name: 'Runaway Dog', w: 25, h: 20 },
  { id: 'coil-snake', name: 'Coil Snake', h: 18 },
  { id: 'ramblin-evil-mushroom', name: "Ramblin' Evil Mushroom", h: 16 },
  { id: 'mobile-sprout', name: 'Mobile Sprout', w: 17, h: 14 },
  { id: 'rowdy-mouse', name: 'Rowdy Mouse', w: 17, h: 15 },
  { id: 'new-age-retro-hippie', name: 'New Age Retro Hippie', w: 19, h: 24 },
  { id: 'lil-ufo', name: "Li'l UFO", h: 12 },
  { id: 'mad-duck', name: 'Mad Duck', h: 24 },
  { id: 'gruff-goat', name: 'Gruff Goat', w: 34, h: 30 },
  { id: 'mad-taxi', name: 'Mad Taxi', w: 34, h: 29 },
  { id: 'chomposaur', name: 'Chomposaur', w: 34, h: 32 },
  { id: 'spiteful-crow', name: 'Spiteful Crow', h: 16 },
  { id: 'annoying-old-party-man', name: 'Annoying Old Party Man', h: 23 },
  { id: 'cranky-lady', name: 'Cranky Lady', h: 24 },
  { id: 'unassuming-local-guy', name: 'Unassuming Local Guy', h: 23 },
  { id: 'mighty-bear', name: 'Mighty Bear', w: 27, h: 31 },
  { id: 'mole-playing-rough', name: 'Mole Playing Rough', h: 14 },
  { id: 'smelly-ghost', name: 'Smelly Ghost', h: 20 },
  { id: 'trick-or-trick-kid', name: 'Trick or Trick Kid', h: 24 },
  { id: 'urban-zombie', name: 'Urban Zombie', h: 24 },
  { id: 'zombie-dog', name: 'Zombie Dog', w: 26, h: 20 },
  { id: 'zombie-possessor', name: 'Zombie Possessor', w: 17, h: 23 },
  { id: 'cave-boy', name: 'Cave Boy', w: 33, h: 32 },
  { id: 'plain-crocodile', name: 'Plain Crocodile', w: 27, h: 25 },
  { id: 'bad-buffalo', name: 'Bad Buffalo', w: 34, h: 31 },
  { id: 'ranboob', name: 'Ranboob', w: 17, h: 24 },
  { id: 'crested-booka', name: 'Crested Booka', w: 24, h: 32 },
  { id: 'gigantic-ant', name: 'Gigantic Ant', h: 15 },
  { id: 'skelpion', name: 'Skelpion', h: 16 },
  { id: 'sentry-robot', name: 'Sentry Robot', h: 24 },
  { id: 'deadly-mouse', name: 'Deadly Mouse', w: 17, h: 15 },
  { id: 'wetnosaur', name: 'Wetnosaur', w: 34, h: 32 },
  { id: 'insane-cultist', name: 'Insane Cultist', h: 24, weight: 0.5 },
  { id: 'foppy', name: 'Foppy', w: 17, h: 13 },
  { id: 'armored-frog', name: 'Armored Frog', w: 15, h: 16 },
  { id: 'slimy-little-pile', name: 'Slimy Little Pile', h: 10 },
  { id: 'dalis-clock', name: "Dali's Clock", h: 23 },
  { id: 'demonic-petunia', name: 'Demonic Petunia', w: 34, h: 23 },
  { id: 'clumsy-robot', name: 'Clumsy Robot', w: 15, h: 21 },
  { id: 'kraken', name: 'Kraken', w: 33, h: 32 },
  { id: 'smilin-sam', name: "Smilin' Sam", h: 24 },
  { id: 'smilin-sphere', name: "Smilin' Sphere", w: 34, h: 32 },
  { id: 'ego-orb', name: 'Ego Orb', w: 34, h: 32 },
  { id: 'guardian-digger', name: 'Guardian Digger', w: 31, h: 32 },
  { id: 'lethal-asp-hieroglyph', name: 'Lethal Asp Hieroglyph', h: 16 },
  { id: 'guardian-hieroglyph', name: 'Guardian Hieroglyph', h: 23 },
  { id: 'manly-fish', name: 'Manly Fish', h: 23 },
  { id: 'zap-eel', name: 'Zap Eel', h: 15 },
  { id: 'noose-man', name: 'Noose Man', w: 14, h: 23 },
  { id: 'crazed-sign', name: 'Crazed Sign', h: 24 },
  { id: 'evil-mani-mani', name: 'Evil Mani Mani', w: 26, h: 32, weight: 0.5 },
  { id: 'abstract-art', name: 'Abstract Art', w: 25, h: 30 },
  { id: 'master-belch', name: 'Master Belch', w: 34, h: 31, weight: 0.5 },
  { id: 'frankystein-mark-ii', name: 'Frankystein Mark II', w: 34, h: 32, weight: 0.5 },
  /* creatures */
  { id: 'monkey', name: 'Monkey', h: 20 },
  { id: 'monkey-with-a-bow', name: 'Monkey with a Bow', h: 23 },
  { id: 'chick', name: 'Chick', w: 14, h: 11 },
  { id: 'mouse-with-a-sign', name: 'Mouse with a Sign', w: 17, h: 24 },
  { id: 'mouse', name: 'Mouse', w: 17, h: 15 },
  { id: 'dog', name: 'Dog', w: 25, h: 20 },
  { id: 'cat', name: 'Cat', w: 23, h: 19 },
  /* townspeople */
  { id: 'old-man', name: 'Old Man', h: 24 },
  { id: 'old-lady', name: 'Old Lady', h: 24 },
  { id: 'gentleman-in-a-bowler', name: 'Gentleman in a Bowler', h: 24 },
  { id: 'man-in-a-blue-cap', name: 'Man in a Blue Cap', w: 19, h: 24 },
  { id: 'bald-businessman', name: 'Bald Businessman', h: 23 },
  { id: 'lady-with-a-big-grin', name: 'Lady with a Big Grin', h: 24 },
  { id: 'blonde-lady-in-green', name: 'Blonde Lady in Green', h: 24 },
  { id: 'mustached-man-in-red', name: 'Mustached Man in Red', h: 24 },
  { id: 'blonde-businessman', name: 'Blonde Businessman', h: 24 },
  { id: 'businessman', name: 'Businessman', h: 24 },
  { id: 'man-in-a-fedora', name: 'Man in a Fedora', h: 24 },
  { id: 'nerd-in-glasses', name: 'Nerd in Glasses', h: 23 },
  { id: 'blonde-kid-in-blue', name: 'Blonde Kid in Blue', h: 24 },
  { id: 'blonde-lady-in-shades', name: 'Blonde Lady in Shades', h: 24 },
  { id: 'girl-in-a-black-cap', name: 'Girl in a Black Cap', h: 24 },
  { id: 'blonde-lady-in-pink', name: 'Blonde Lady in Pink', h: 24 },
  { id: 'red-haired-guy', name: 'Red-Haired Guy', h: 23 },
  { id: 'blonde-boy', name: 'Blonde Boy', h: 24 },
  { id: 'tourist-in-a-loud-shirt', name: 'Tourist in a Loud Shirt', h: 24 },
  { id: 'dancer-with-a-fruit-hat', name: 'Dancer with a Fruit Hat', h: 24 },
  { id: 'bellhop', name: 'Bellhop', h: 24 },
  { id: 'police-officer', name: 'Police Officer', h: 24 },
  { id: 'man-in-a-red-cap', name: 'Man in a Red Cap', h: 24 },
  { id: 'street-musician', name: 'Street Musician', h: 23 },
  { id: 'musician-in-gold', name: 'Musician in Gold', h: 24 },
  { id: 'tough-guy', name: 'Tough Guy', h: 24 },
  { id: 'beach-boy', name: 'Beach Boy', h: 24 },
  { id: 'beach-girl', name: 'Beach Girl', h: 24 },
  { id: 'explorer', name: 'Explorer', h: 24 },
  { id: 'hotel-staff', name: 'Hotel Staff', h: 24 },
  { id: 'punk-with-a-mohawk', name: 'Punk with a Mohawk', h: 24 },
  { id: 'beach-guy', name: 'Beach Guy', h: 24 },
  { id: 'blonde-beach-lady', name: 'Blonde Beach Lady', h: 24 },
  { id: 'market-vendor', name: 'Market Vendor', h: 24 },
  { id: 'dalaam-lady', name: 'Dalaam Lady', h: 24 },
  { id: 'sailor', name: 'Sailor', h: 24 },
  { id: 'bearded-guy', name: 'Bearded Guy', h: 24 },
  { id: 'hooded-elder', name: 'Hooded Elder', h: 24 },
  { id: 'scaraba-local', name: 'Scaraba Local', h: 22 },
  { id: 'scaraba-merchant', name: 'Scaraba Merchant', h: 23 },
  { id: 'man-in-a-white-cap', name: 'Man in a White Cap', h: 23 },
  { id: 'monk', name: 'Monk', h: 24 },
  { id: 'clown', name: 'Clown', h: 24 },
  { id: 'bodyguard', name: 'Bodyguard', h: 24 },
  { id: 'blonde-woman-in-black', name: 'Blonde Woman in Black', w: 17, h: 24 },
  { id: 'kid-in-blue', name: 'Kid in Blue', h: 24 },
  { id: 'red-haired-kid', name: 'Red-Haired Kid', h: 24 },
  { id: 'blonde-kid-in-white', name: 'Blonde Kid in White', h: 24 },
  { id: 'messy-haired-kid', name: 'Messy-Haired Kid', h: 24 },
  { id: 'girl-with-a-headband', name: 'Girl with a Headband', h: 24 },
  { id: 'ginger-boy', name: 'Ginger Boy', h: 24 },
  { id: 'guy-in-red', name: 'Guy in Red', h: 23 },
  { id: 'girl-with-pigtails', name: 'Girl with Pigtails', h: 24 },
  { id: 'girl-in-a-straw-hat', name: 'Girl in a Straw Hat', h: 24 },
  { id: 'blonde-girl-in-yellow', name: 'Blonde Girl in Yellow', h: 24 },
  { id: 'kid-in-a-blue-cap', name: 'Kid in a Blue Cap', h: 22 },
  { id: 'kid-in-a-red-cap', name: 'Kid in a Red Cap', h: 22 },
  { id: 'kid-in-a-bowler', name: 'Kid in a Bowler', h: 21 },
  { id: 'fisherman', name: 'Fisherman', h: 23 },
  { id: 'little-girl-with-a-bow', name: 'Little Girl with a Bow', h: 24 },
  { id: 'little-girl-in-pink', name: 'Little Girl in Pink', w: 17, h: 22 },
  { id: 'cook', name: 'Cook', h: 24 },
  { id: 'waitress', name: 'Waitress', h: 24 },
  { id: 'doctor', name: 'Doctor', h: 24 },
  { id: 'nurse', name: 'Nurse', h: 24 },
  { id: 'hospital-nurse', name: 'Hospital Nurse', h: 24 },
  { id: 'lady-in-glasses', name: 'Lady in Glasses', h: 23 },
  { id: 'little-girl-with-pink-bows', name: 'Little Girl with Pink Bows', h: 24 },
  { id: 'lady-in-pink', name: 'Lady in Pink', h: 24 },
  { id: 'lady-in-a-black-dress', name: 'Lady in a Black Dress', w: 17, h: 24 },
  { id: 'bald-old-man', name: 'Bald Old Man', h: 24 },
  { id: 'rich-old-man', name: 'Rich Old Man', h: 24 },
  { id: 'businessman-in-glasses', name: 'Businessman in Glasses', h: 24 },
  { id: 'man-in-blue', name: 'Man in Blue', h: 24 },
  { id: 'mustached-man-in-green', name: 'Mustached Man in Green', h: 24 },
  { id: 'girl-in-a-strawberry-hat', name: 'Girl in a Strawberry Hat', h: 24 },
  { id: 'old-man-in-blue', name: 'Old Man in Blue', h: 24 },
  { id: 'old-veteran', name: 'Old Veteran', h: 24 },
  { id: 'construction-worker', name: 'Construction Worker', h: 24 },
  { id: 'guy-in-a-white-tee', name: 'Guy in a White Tee', h: 23 },
  { id: 'kid-in-orange', name: 'Kid in Orange', h: 24 },
  { id: 'kid-in-red', name: 'Kid in Red', h: 24 },
  { id: 'man-in-overalls', name: 'Man in Overalls', h: 23 },
  { id: 'lady-in-a-pink-hat', name: 'Lady in a Pink Hat', h: 24 },
  { id: 'boy-in-stripes', name: 'Boy in Stripes', h: 24 },
  { id: 'blonde-girl-in-green', name: 'Blonde Girl in Green', h: 24 },
  { id: 'girl-in-a-blue-dress', name: 'Girl in a Blue Dress', h: 24 },
];
