/* Who can turn up in the bottom-right corner of home.

   One is drawn at random on every visit, weighted: Mr. Saturn and the
   party often, the townspeople and the enemies now and then, a few rare
   ones hardly ever. Each is a strip of eight frames, all one size — back,
   right, front, left, two of each — cut from the EarthBound sheets on The
   Spriters Resource into images/eb/cast/; the enemies that never walk in
   the game repeat their one or two frames. w and h are a frame's size in
   the sprite's own pixels. What everyone says is in cast-lines.json, so
   this file stays small enough to load with the page. */
export const CAST = [
  { id: 'saturn', name: 'Mr. Saturn', src: 'images/eb/saturn.png', w: 18, h: 22, weight: 4, font: 'saturn' },
  /* the party */
  { id: 'ness', name: 'Ness', src: 'images/eb/cast/ness.png', w: 18, h: 24, weight: 2 },
  { id: 'paula', name: 'Paula', src: 'images/eb/cast/paula.png', w: 18, h: 24, weight: 2 },
  { id: 'jeff', name: 'Jeff', src: 'images/eb/cast/jeff.png', w: 18, h: 24, weight: 2 },
  { id: 'poo', name: 'Poo', src: 'images/eb/cast/poo.png', w: 18, h: 24, weight: 2 },
  /* people with names */
  { id: 'captain-strong', name: 'Captain Strong', src: 'images/eb/cast/captain-strong.png', w: 18, h: 24 },
  { id: 'pokey', name: 'Pokey', src: 'images/eb/cast/pokey.png', w: 18, h: 24, weight: 0.5 },
  { id: 'king', name: 'King', src: 'images/eb/cast/king.png', w: 26, h: 20 },
  { id: 'bubble-monkey', name: 'Bubble Monkey', src: 'images/eb/cast/bubble-monkey.png', w: 18, h: 23 },
  { id: 'tony', name: 'Tony', src: 'images/eb/cast/tony.png', w: 18, h: 24 },
  { id: 'picky', name: 'Picky', src: 'images/eb/cast/picky.png', w: 18, h: 22 },
  { id: 'brick-road', name: 'Brick Road', src: 'images/eb/cast/brick-road.png', w: 18, h: 24 },
  { id: 'tenda', name: 'Tenda', src: 'images/eb/cast/tenda.png', w: 18, h: 17 },
  { id: 'everdred', name: 'Everdred', src: 'images/eb/cast/everdred.png', w: 18, h: 24, weight: 0.5 },
  { id: 'the-star-master', name: 'The Star Master', src: 'images/eb/cast/the-star-master.png', w: 18, h: 24, weight: 0.25 },
  { id: 'hint-man', name: 'Hint Man', src: 'images/eb/cast/hint-man.png', w: 18, h: 24 },
  { id: 'nesss-mom', name: "Ness's Mom", src: 'images/eb/cast/nesss-mom.png', w: 18, h: 24 },
  { id: 'tracy', name: 'Tracy', src: 'images/eb/cast/tracy.png', w: 18, h: 24 },
  { id: 'arms-dealer', name: 'Arms Dealer', src: 'images/eb/cast/arms-dealer.png', w: 18, h: 24 },
  { id: 'escargo-express-delivery-man', name: 'Escargo Express Delivery Man', src: 'images/eb/cast/escargo-express-delivery-man.png', w: 18, h: 24 },
  { id: 'slot-machine-brother', name: 'Slot Machine Brother', src: 'images/eb/cast/slot-machine-brother.png', w: 18, h: 24 },
  { id: 'gonzales', name: 'Gonzales', src: 'images/eb/cast/gonzales.png', w: 18, h: 24 },
  { id: 'aloysius-minch', name: 'Aloysius Minch', src: 'images/eb/cast/aloysius-minch.png', w: 18, h: 24 },
  { id: 'lardna-minch', name: 'Lardna Minch', src: 'images/eb/cast/lardna-minch.png', w: 18, h: 24 },
  { id: 'frank-fly', name: 'Frank Fly', src: 'images/eb/cast/frank-fly.png', w: 18, h: 24 },
  { id: 'mr-carpainter', name: 'Mr. Carpainter', src: 'images/eb/cast/mr-carpainter.png', w: 18, h: 24 },
  { id: 'dr-andonuts', name: 'Dr. Andonuts', src: 'images/eb/cast/dr-andonuts.png', w: 18, h: 23, weight: 0.5 },
  { id: 'runaway-five', name: 'Runaway Five', src: 'images/eb/cast/runaway-five.png', w: 18, h: 23, weight: 0.25 },
  { id: 'runaway-five-2', name: 'Runaway Five', src: 'images/eb/cast/runaway-five-2.png', w: 18, h: 24, weight: 0.25 },
  { id: 'runaway-five-3', name: 'Runaway Five', src: 'images/eb/cast/runaway-five-3.png', w: 18, h: 23, weight: 0.25 },
  { id: 'runaway-five-4', name: 'Runaway Five', src: 'images/eb/cast/runaway-five-4.png', w: 18, h: 23, weight: 0.25 },
  /* enemies */
  { id: 'runaway-dog', name: 'Runaway Dog', src: 'images/eb/cast/runaway-dog.png', w: 25, h: 20 },
  { id: 'coil-snake', name: 'Coil Snake', src: 'images/eb/cast/coil-snake.png', w: 18, h: 18 },
  { id: 'ramblin-evil-mushroom', name: "Ramblin' Evil Mushroom", src: 'images/eb/cast/ramblin-evil-mushroom.png', w: 18, h: 16 },
  { id: 'mobile-sprout', name: 'Mobile Sprout', src: 'images/eb/cast/mobile-sprout.png', w: 17, h: 14 },
  { id: 'rowdy-mouse', name: 'Rowdy Mouse', src: 'images/eb/cast/rowdy-mouse.png', w: 17, h: 15 },
  { id: 'new-age-retro-hippie', name: 'New Age Retro Hippie', src: 'images/eb/cast/new-age-retro-hippie.png', w: 19, h: 24 },
  { id: 'lil-ufo', name: "Li'l UFO", src: 'images/eb/cast/lil-ufo.png', w: 18, h: 12 },
  { id: 'mad-duck', name: 'Mad Duck', src: 'images/eb/cast/mad-duck.png', w: 18, h: 24 },
  { id: 'gruff-goat', name: 'Gruff Goat', src: 'images/eb/cast/gruff-goat.png', w: 34, h: 30 },
  { id: 'mad-taxi', name: 'Mad Taxi', src: 'images/eb/cast/mad-taxi.png', w: 34, h: 29 },
  { id: 'chomposaur', name: 'Chomposaur', src: 'images/eb/cast/chomposaur.png', w: 34, h: 32 },
  { id: 'spiteful-crow', name: 'Spiteful Crow', src: 'images/eb/cast/spiteful-crow.png', w: 18, h: 16 },
  { id: 'annoying-old-party-man', name: 'Annoying Old Party Man', src: 'images/eb/cast/annoying-old-party-man.png', w: 18, h: 23 },
  { id: 'cranky-lady', name: 'Cranky Lady', src: 'images/eb/cast/cranky-lady.png', w: 18, h: 24 },
  { id: 'unassuming-local-guy', name: 'Unassuming Local Guy', src: 'images/eb/cast/unassuming-local-guy.png', w: 18, h: 23 },
  { id: 'mighty-bear', name: 'Mighty Bear', src: 'images/eb/cast/mighty-bear.png', w: 27, h: 31 },
  { id: 'mole-playing-rough', name: 'Mole Playing Rough', src: 'images/eb/cast/mole-playing-rough.png', w: 18, h: 14 },
  { id: 'smelly-ghost', name: 'Smelly Ghost', src: 'images/eb/cast/smelly-ghost.png', w: 18, h: 20 },
  { id: 'trick-or-trick-kid', name: 'Trick or Trick Kid', src: 'images/eb/cast/trick-or-trick-kid.png', w: 18, h: 24 },
  { id: 'urban-zombie', name: 'Urban Zombie', src: 'images/eb/cast/urban-zombie.png', w: 18, h: 24 },
  { id: 'zombie-dog', name: 'Zombie Dog', src: 'images/eb/cast/zombie-dog.png', w: 26, h: 20 },
  { id: 'zombie-possessor', name: 'Zombie Possessor', src: 'images/eb/cast/zombie-possessor.png', w: 17, h: 23 },
  { id: 'cave-boy', name: 'Cave Boy', src: 'images/eb/cast/cave-boy.png', w: 33, h: 32 },
  { id: 'plain-crocodile', name: 'Plain Crocodile', src: 'images/eb/cast/plain-crocodile.png', w: 27, h: 25 },
  { id: 'bad-buffalo', name: 'Bad Buffalo', src: 'images/eb/cast/bad-buffalo.png', w: 34, h: 31 },
  { id: 'ranboob', name: 'Ranboob', src: 'images/eb/cast/ranboob.png', w: 17, h: 24 },
  { id: 'crested-booka', name: 'Crested Booka', src: 'images/eb/cast/crested-booka.png', w: 24, h: 32 },
  { id: 'gigantic-ant', name: 'Gigantic Ant', src: 'images/eb/cast/gigantic-ant.png', w: 18, h: 15 },
  { id: 'skelpion', name: 'Skelpion', src: 'images/eb/cast/skelpion.png', w: 18, h: 16 },
  { id: 'sentry-robot', name: 'Sentry Robot', src: 'images/eb/cast/sentry-robot.png', w: 18, h: 24 },
  { id: 'deadly-mouse', name: 'Deadly Mouse', src: 'images/eb/cast/deadly-mouse.png', w: 17, h: 15 },
  { id: 'wetnosaur', name: 'Wetnosaur', src: 'images/eb/cast/wetnosaur.png', w: 34, h: 32 },
  { id: 'insane-cultist', name: 'Insane Cultist', src: 'images/eb/cast/insane-cultist.png', w: 18, h: 24, weight: 0.5 },
  { id: 'foppy', name: 'Foppy', src: 'images/eb/cast/foppy.png', w: 17, h: 13 },
  { id: 'armored-frog', name: 'Armored Frog', src: 'images/eb/cast/armored-frog.png', w: 15, h: 16 },
  { id: 'slimy-little-pile', name: 'Slimy Little Pile', src: 'images/eb/cast/slimy-little-pile.png', w: 18, h: 10 },
  { id: 'dalis-clock', name: "Dali's Clock", src: 'images/eb/cast/dalis-clock.png', w: 18, h: 23 },
  { id: 'demonic-petunia', name: 'Demonic Petunia', src: 'images/eb/cast/demonic-petunia.png', w: 34, h: 23 },
  { id: 'clumsy-robot', name: 'Clumsy Robot', src: 'images/eb/cast/clumsy-robot.png', w: 15, h: 21 },
  { id: 'kraken', name: 'Kraken', src: 'images/eb/cast/kraken.png', w: 33, h: 32 },
  { id: 'smilin-sam', name: "Smilin' Sam", src: 'images/eb/cast/smilin-sam.png', w: 18, h: 24 },
  { id: 'smilin-sphere', name: "Smilin' Sphere", src: 'images/eb/cast/smilin-sphere.png', w: 34, h: 32 },
  { id: 'ego-orb', name: 'Ego Orb', src: 'images/eb/cast/ego-orb.png', w: 34, h: 32 },
  { id: 'guardian-digger', name: 'Guardian Digger', src: 'images/eb/cast/guardian-digger.png', w: 31, h: 32 },
  { id: 'lethal-asp-hieroglyph', name: 'Lethal Asp Hieroglyph', src: 'images/eb/cast/lethal-asp-hieroglyph.png', w: 18, h: 16 },
  { id: 'guardian-hieroglyph', name: 'Guardian Hieroglyph', src: 'images/eb/cast/guardian-hieroglyph.png', w: 18, h: 23 },
  { id: 'manly-fish', name: 'Manly Fish', src: 'images/eb/cast/manly-fish.png', w: 18, h: 23 },
  { id: 'zap-eel', name: 'Zap Eel', src: 'images/eb/cast/zap-eel.png', w: 18, h: 15 },
  { id: 'noose-man', name: 'Noose Man', src: 'images/eb/cast/noose-man.png', w: 14, h: 23 },
  { id: 'crazed-sign', name: 'Crazed Sign', src: 'images/eb/cast/crazed-sign.png', w: 18, h: 24 },
  { id: 'evil-mani-mani', name: 'Evil Mani Mani', src: 'images/eb/cast/evil-mani-mani.png', w: 26, h: 32, weight: 0.5 },
  { id: 'abstract-art', name: 'Abstract Art', src: 'images/eb/cast/abstract-art.png', w: 25, h: 30 },
  { id: 'master-belch', name: 'Master Belch', src: 'images/eb/cast/master-belch.png', w: 34, h: 31, weight: 0.5 },
  { id: 'frankystein-mark-ii', name: 'Frankystein Mark II', src: 'images/eb/cast/frankystein-mark-ii.png', w: 34, h: 32, weight: 0.5 },
  /* creatures */
  { id: 'monkey', name: 'Monkey', src: 'images/eb/cast/monkey.png', w: 18, h: 20 },
  { id: 'monkey-with-a-bow', name: 'Monkey with a Bow', src: 'images/eb/cast/monkey-with-a-bow.png', w: 18, h: 23 },
  { id: 'chick', name: 'Chick', src: 'images/eb/cast/chick.png', w: 14, h: 11 },
  { id: 'mouse-with-a-sign', name: 'Mouse with a Sign', src: 'images/eb/cast/mouse-with-a-sign.png', w: 17, h: 24 },
  { id: 'mouse', name: 'Mouse', src: 'images/eb/cast/mouse.png', w: 17, h: 15 },
  { id: 'dog', name: 'Dog', src: 'images/eb/cast/dog.png', w: 25, h: 20 },
  { id: 'cat', name: 'Cat', src: 'images/eb/cast/cat.png', w: 23, h: 19 },
  /* townspeople */
  { id: 'old-man', name: 'Old Man', src: 'images/eb/cast/old-man.png', w: 18, h: 24 },
  { id: 'old-lady', name: 'Old Lady', src: 'images/eb/cast/old-lady.png', w: 18, h: 24 },
  { id: 'gentleman-in-a-bowler', name: 'Gentleman in a Bowler', src: 'images/eb/cast/gentleman-in-a-bowler.png', w: 18, h: 24 },
  { id: 'man-in-a-blue-cap', name: 'Man in a Blue Cap', src: 'images/eb/cast/man-in-a-blue-cap.png', w: 19, h: 24 },
  { id: 'bald-businessman', name: 'Bald Businessman', src: 'images/eb/cast/bald-businessman.png', w: 18, h: 23 },
  { id: 'lady-with-a-big-grin', name: 'Lady with a Big Grin', src: 'images/eb/cast/lady-with-a-big-grin.png', w: 18, h: 24 },
  { id: 'blonde-lady-in-green', name: 'Blonde Lady in Green', src: 'images/eb/cast/blonde-lady-in-green.png', w: 18, h: 24 },
  { id: 'mustached-man-in-red', name: 'Mustached Man in Red', src: 'images/eb/cast/mustached-man-in-red.png', w: 18, h: 24 },
  { id: 'blonde-businessman', name: 'Blonde Businessman', src: 'images/eb/cast/blonde-businessman.png', w: 18, h: 24 },
  { id: 'businessman', name: 'Businessman', src: 'images/eb/cast/businessman.png', w: 18, h: 24 },
  { id: 'man-in-a-fedora', name: 'Man in a Fedora', src: 'images/eb/cast/man-in-a-fedora.png', w: 18, h: 24 },
  { id: 'nerd-in-glasses', name: 'Nerd in Glasses', src: 'images/eb/cast/nerd-in-glasses.png', w: 18, h: 23 },
  { id: 'blonde-kid-in-blue', name: 'Blonde Kid in Blue', src: 'images/eb/cast/blonde-kid-in-blue.png', w: 18, h: 24 },
  { id: 'blonde-lady-in-shades', name: 'Blonde Lady in Shades', src: 'images/eb/cast/blonde-lady-in-shades.png', w: 18, h: 24 },
  { id: 'girl-in-a-black-cap', name: 'Girl in a Black Cap', src: 'images/eb/cast/girl-in-a-black-cap.png', w: 18, h: 24 },
  { id: 'blonde-lady-in-pink', name: 'Blonde Lady in Pink', src: 'images/eb/cast/blonde-lady-in-pink.png', w: 18, h: 24 },
  { id: 'red-haired-guy', name: 'Red-Haired Guy', src: 'images/eb/cast/red-haired-guy.png', w: 18, h: 23 },
  { id: 'blonde-boy', name: 'Blonde Boy', src: 'images/eb/cast/blonde-boy.png', w: 18, h: 24 },
  { id: 'tourist-in-a-loud-shirt', name: 'Tourist in a Loud Shirt', src: 'images/eb/cast/tourist-in-a-loud-shirt.png', w: 18, h: 24 },
  { id: 'dancer-with-a-fruit-hat', name: 'Dancer with a Fruit Hat', src: 'images/eb/cast/dancer-with-a-fruit-hat.png', w: 18, h: 24 },
  { id: 'bellhop', name: 'Bellhop', src: 'images/eb/cast/bellhop.png', w: 18, h: 24 },
  { id: 'police-officer', name: 'Police Officer', src: 'images/eb/cast/police-officer.png', w: 18, h: 24 },
  { id: 'man-in-a-red-cap', name: 'Man in a Red Cap', src: 'images/eb/cast/man-in-a-red-cap.png', w: 18, h: 24 },
  { id: 'street-musician', name: 'Street Musician', src: 'images/eb/cast/street-musician.png', w: 18, h: 23 },
  { id: 'musician-in-gold', name: 'Musician in Gold', src: 'images/eb/cast/musician-in-gold.png', w: 18, h: 24 },
  { id: 'tough-guy', name: 'Tough Guy', src: 'images/eb/cast/tough-guy.png', w: 18, h: 24 },
  { id: 'beach-boy', name: 'Beach Boy', src: 'images/eb/cast/beach-boy.png', w: 18, h: 24 },
  { id: 'beach-girl', name: 'Beach Girl', src: 'images/eb/cast/beach-girl.png', w: 18, h: 24 },
  { id: 'explorer', name: 'Explorer', src: 'images/eb/cast/explorer.png', w: 18, h: 24 },
  { id: 'hotel-staff', name: 'Hotel Staff', src: 'images/eb/cast/hotel-staff.png', w: 18, h: 24 },
  { id: 'punk-with-a-mohawk', name: 'Punk with a Mohawk', src: 'images/eb/cast/punk-with-a-mohawk.png', w: 18, h: 24 },
  { id: 'beach-guy', name: 'Beach Guy', src: 'images/eb/cast/beach-guy.png', w: 18, h: 24 },
  { id: 'blonde-beach-lady', name: 'Blonde Beach Lady', src: 'images/eb/cast/blonde-beach-lady.png', w: 18, h: 24 },
  { id: 'market-vendor', name: 'Market Vendor', src: 'images/eb/cast/market-vendor.png', w: 18, h: 24 },
  { id: 'dalaam-lady', name: 'Dalaam Lady', src: 'images/eb/cast/dalaam-lady.png', w: 18, h: 24 },
  { id: 'sailor', name: 'Sailor', src: 'images/eb/cast/sailor.png', w: 18, h: 24 },
  { id: 'bearded-guy', name: 'Bearded Guy', src: 'images/eb/cast/bearded-guy.png', w: 18, h: 24 },
  { id: 'hooded-elder', name: 'Hooded Elder', src: 'images/eb/cast/hooded-elder.png', w: 18, h: 24 },
  { id: 'scaraba-local', name: 'Scaraba Local', src: 'images/eb/cast/scaraba-local.png', w: 18, h: 22 },
  { id: 'scaraba-merchant', name: 'Scaraba Merchant', src: 'images/eb/cast/scaraba-merchant.png', w: 18, h: 23 },
  { id: 'man-in-a-white-cap', name: 'Man in a White Cap', src: 'images/eb/cast/man-in-a-white-cap.png', w: 18, h: 23 },
  { id: 'monk', name: 'Monk', src: 'images/eb/cast/monk.png', w: 18, h: 24 },
  { id: 'clown', name: 'Clown', src: 'images/eb/cast/clown.png', w: 18, h: 24 },
  { id: 'bodyguard', name: 'Bodyguard', src: 'images/eb/cast/bodyguard.png', w: 18, h: 24 },
  { id: 'blonde-woman-in-black', name: 'Blonde Woman in Black', src: 'images/eb/cast/blonde-woman-in-black.png', w: 17, h: 24 },
  { id: 'kid-in-blue', name: 'Kid in Blue', src: 'images/eb/cast/kid-in-blue.png', w: 18, h: 24 },
  { id: 'red-haired-kid', name: 'Red-Haired Kid', src: 'images/eb/cast/red-haired-kid.png', w: 18, h: 24 },
  { id: 'blonde-kid-in-white', name: 'Blonde Kid in White', src: 'images/eb/cast/blonde-kid-in-white.png', w: 18, h: 24 },
  { id: 'messy-haired-kid', name: 'Messy-Haired Kid', src: 'images/eb/cast/messy-haired-kid.png', w: 18, h: 24 },
  { id: 'girl-with-a-headband', name: 'Girl with a Headband', src: 'images/eb/cast/girl-with-a-headband.png', w: 18, h: 24 },
  { id: 'ginger-boy', name: 'Ginger Boy', src: 'images/eb/cast/ginger-boy.png', w: 18, h: 24 },
  { id: 'guy-in-red', name: 'Guy in Red', src: 'images/eb/cast/guy-in-red.png', w: 18, h: 23 },
  { id: 'girl-with-pigtails', name: 'Girl with Pigtails', src: 'images/eb/cast/girl-with-pigtails.png', w: 18, h: 24 },
  { id: 'girl-in-a-straw-hat', name: 'Girl in a Straw Hat', src: 'images/eb/cast/girl-in-a-straw-hat.png', w: 18, h: 24 },
  { id: 'blonde-girl-in-yellow', name: 'Blonde Girl in Yellow', src: 'images/eb/cast/blonde-girl-in-yellow.png', w: 18, h: 24 },
  { id: 'kid-in-a-blue-cap', name: 'Kid in a Blue Cap', src: 'images/eb/cast/kid-in-a-blue-cap.png', w: 18, h: 22 },
  { id: 'kid-in-a-red-cap', name: 'Kid in a Red Cap', src: 'images/eb/cast/kid-in-a-red-cap.png', w: 18, h: 22 },
  { id: 'kid-in-a-bowler', name: 'Kid in a Bowler', src: 'images/eb/cast/kid-in-a-bowler.png', w: 18, h: 21 },
  { id: 'fisherman', name: 'Fisherman', src: 'images/eb/cast/fisherman.png', w: 18, h: 23 },
  { id: 'little-girl-with-a-bow', name: 'Little Girl with a Bow', src: 'images/eb/cast/little-girl-with-a-bow.png', w: 18, h: 24 },
  { id: 'little-girl-in-pink', name: 'Little Girl in Pink', src: 'images/eb/cast/little-girl-in-pink.png', w: 17, h: 22 },
  { id: 'cook', name: 'Cook', src: 'images/eb/cast/cook.png', w: 18, h: 24 },
  { id: 'waitress', name: 'Waitress', src: 'images/eb/cast/waitress.png', w: 18, h: 24 },
  { id: 'doctor', name: 'Doctor', src: 'images/eb/cast/doctor.png', w: 18, h: 24 },
  { id: 'nurse', name: 'Nurse', src: 'images/eb/cast/nurse.png', w: 18, h: 24 },
  { id: 'hospital-nurse', name: 'Hospital Nurse', src: 'images/eb/cast/hospital-nurse.png', w: 18, h: 24 },
  { id: 'lady-in-glasses', name: 'Lady in Glasses', src: 'images/eb/cast/lady-in-glasses.png', w: 18, h: 23 },
  { id: 'little-girl-with-pink-bows', name: 'Little Girl with Pink Bows', src: 'images/eb/cast/little-girl-with-pink-bows.png', w: 18, h: 24 },
  { id: 'lady-in-pink', name: 'Lady in Pink', src: 'images/eb/cast/lady-in-pink.png', w: 18, h: 24 },
  { id: 'lady-in-a-black-dress', name: 'Lady in a Black Dress', src: 'images/eb/cast/lady-in-a-black-dress.png', w: 17, h: 24 },
  { id: 'bald-old-man', name: 'Bald Old Man', src: 'images/eb/cast/bald-old-man.png', w: 18, h: 24 },
  { id: 'rich-old-man', name: 'Rich Old Man', src: 'images/eb/cast/rich-old-man.png', w: 18, h: 24 },
  { id: 'businessman-in-glasses', name: 'Businessman in Glasses', src: 'images/eb/cast/businessman-in-glasses.png', w: 18, h: 24 },
  { id: 'man-in-blue', name: 'Man in Blue', src: 'images/eb/cast/man-in-blue.png', w: 18, h: 24 },
  { id: 'mustached-man-in-green', name: 'Mustached Man in Green', src: 'images/eb/cast/mustached-man-in-green.png', w: 18, h: 24 },
  { id: 'girl-in-a-strawberry-hat', name: 'Girl in a Strawberry Hat', src: 'images/eb/cast/girl-in-a-strawberry-hat.png', w: 18, h: 24 },
  { id: 'old-man-in-blue', name: 'Old Man in Blue', src: 'images/eb/cast/old-man-in-blue.png', w: 18, h: 24 },
  { id: 'old-veteran', name: 'Old Veteran', src: 'images/eb/cast/old-veteran.png', w: 18, h: 24 },
  { id: 'construction-worker', name: 'Construction Worker', src: 'images/eb/cast/construction-worker.png', w: 18, h: 24 },
  { id: 'guy-in-a-white-tee', name: 'Guy in a White Tee', src: 'images/eb/cast/guy-in-a-white-tee.png', w: 18, h: 23 },
  { id: 'kid-in-orange', name: 'Kid in Orange', src: 'images/eb/cast/kid-in-orange.png', w: 18, h: 24 },
  { id: 'kid-in-red', name: 'Kid in Red', src: 'images/eb/cast/kid-in-red.png', w: 18, h: 24 },
  { id: 'man-in-overalls', name: 'Man in Overalls', src: 'images/eb/cast/man-in-overalls.png', w: 18, h: 23 },
  { id: 'lady-in-a-pink-hat', name: 'Lady in a Pink Hat', src: 'images/eb/cast/lady-in-a-pink-hat.png', w: 18, h: 24 },
  { id: 'boy-in-stripes', name: 'Boy in Stripes', src: 'images/eb/cast/boy-in-stripes.png', w: 18, h: 24 },
  { id: 'blonde-girl-in-green', name: 'Blonde Girl in Green', src: 'images/eb/cast/blonde-girl-in-green.png', w: 18, h: 24 },
  { id: 'girl-in-a-blue-dress', name: 'Girl in a Blue Dress', src: 'images/eb/cast/girl-in-a-blue-dress.png', w: 18, h: 24 },
];
